### ISSUE TITLE
ieCompat not working

### ISSUE THREAD

**Issue by Macmee** [gruntjs/grunt-contrib-less#188] opened 2014-06-18 19:46 UTC
less: {
            ieCompatFalse: {
                options: {
                    ieCompat: false
                },
                files: {
                    'src/compiled.css': ['src/css/style.css']
                }
            }
        }

produces the following output with grunt:

Skipped data-uri embedding of src/liberationSans/LiberationSans-Regular.ttf because its size (130KB) exceeds IE8-safe 32KB!
Skipped data-uri embedding of src/liberationSans/LiberationSans-Bold.ttf because its size (130KB) exceeds IE8-safe 32KB!
Skipped data-uri embedding of src/images/big_loader.gif because its size (35KB) exceeds IE8-safe 32KB!
Skipped data-uri embedding of src/images/big_loader.gif because its size (35KB) exceeds IE8-safe 32KB!
Skipped data-uri embedding of src/images/big_loader.gif because its size (35KB) exceeds IE8-safe 32KB!
Skipped data-uri embedding of src/images/big_loader.gif because its size (35KB) exceeds IE8-safe 32KB!
Skipped data-uri embedding of src/images/flags.png because its size (85KB) exceeds IE8-safe 32KB!
Skipped data-uri embedding of src/images/big_loader.gif because its size (35KB) exceeds IE8-safe 32KB!

And yet these should not be skipped because ieCompat is false.

**Comment by lukeapage** [comment] 2015-01-04 13:17
duplicate of #154

**Closed by lukeapage** 2015-01-04 13:17 UTC
