### ISSUE TITLE
sourceMap options generates incorrect sourceMapUrl

### ISSUE THREAD

**Issue by MartinSGill** [gruntjs/grunt-contrib-less#236] opened 2015-01-01 22:14 UTC
When calling lessc directly, the sourceMappingURL is **correctly** generated as:

```ps1
.\node_modules\.bin\lessc.cmd ./src/css/modern.less ./src/css/modern.css `
>>> --source-map
```

```css
/*# sourceMappingURL=modern.css.map */
```

when using grunt-contrib-less the sourceMappingURL is **incorrect**:

```javascript
	 less: {
	     release: {
	         options: {
	             sourceMap: true
	         },
	         files: [
	             { src: ["./src/css/modern.less"], dest: './src/css/modern.css' }
	         ]
	     }
	 }
```

results in:

```css
/*# sourceMappingURL=./src/css/modern.css.map */
```

I believe both of these should be generating the same sourceMappingURL.

This is important as my files are served from `/css` , not `/src/css/`, additionally I have many less files that need to be compiled to css, and each needs its own map file, therefore I cannot use the sourceMapUrl option in the grunt config.

**Comment by MarkyMarkNo1** [comment] 2015-01-01 23:34
I have to confirm that issue for v1.0.0. Furthermore, `sourceMapRootpath` as well as `sourceMapBasepath` **options don't work anymore, they just have no effect**. Worked in v0.12.0.

Thanks and regards.

**Comment by PeterSelvaraj** [comment] 2015-01-02 07:00
I have to confirm Mark's observations. I have switched back to v0.12.0 and can confirm these issues don't exist in v0.12.0

**Comment by lukeapage** [comment] 2015-01-04 14:12
> I have to confirm that issue for v1.0.0. Furthermore, sourceMapRootpath as well as sourceMapBasepath options don't work anymore, they just have no effect. Worked in v0.12.0.

I've just been looking at the tests and we test that sourceMapBasepath works - can you be more specific about what is wrong?

You can specify the sourceMapURL and thereby override the default value for it.

**Comment by MartinSGill** [comment] 2015-01-04 14:43
> You can specify the sourceMapURL and thereby override the default value for it.

This isn't much use for me, as it's not generic, e.g:

```javascript
 less: {
     release: {
         options: {
             sourceMap: true,
             sourceMapURL: 'modern.less'
         },
         files: [
             { src: ["./src/css/modern.less"], dest: './src/css/modern.css' },
             { src: ["./src/css/simple_default.less"], dest: './src/css/simple_default.css' },
             { src: ["./src/css/simple_solarized_dark.less"], dest: './src/css/simple_solarized_dark.css' },
             { src: ["./src/css/simple_solarized_light.less"], dest: './src/css/simple_solarized_light.css' }
         ]
     }
 },

```

results in every file pointing to a single map, which is wrong for all but one file. An entry for every single file, becomes a maintenance nightmare.

more useful might be:

```javascript
sourceMapURL: '$1'
```

where $1 is the file name. Or just get it to behave the way LESS actually does, which is reference the map file correctly (in a relative way).

I thought sourceMapBase path might be useful, but it's meant for references **in** the map file, not for references **to** the map file.

The problem for me is that the workaround is to run LESS directly.

> I've just been looking at the tests and we test that sourceMapBasepath works - can you be more specific about what is wrong?

Shouldn't the tests also ensure that identical configuration in grunt-contrib-less produce identical results when LESS is run directly?

**Comment by MarkyMarkNo1** [comment] 2015-01-05 15:48
I have to generate less like

```javascript
less: {
  options: {
    sourceMap: true,
    sourceMapRootpath: '/',
    sourceMapBasepath: 'www'
  },
  styles: {
    options: {
      sourceMapFilename: 'www/styles/styles.css.map'
    },
    files: {
      'www/styles/styles.css': 'www/styles/styles.less'
    }
  }
}
```

`www` is the http root, so the source mapping url needs to be

```css
/*# sourceMappingURL=/styles/custom.css.map */
```

This always worked, since `sourceMapRootpath` and `sourceMapBasepath` *were utilized* for the `sourceMappingURL`.

Unfortunately, this operation *fails since v1.0.0*. The task above would dumbly generate 

```css
/*# sourceMappingURL='www/styles/custom.css.map */
```

which is unexpected and different. So, just like @MartinSGill , I had to revert to v0.12.0. 

*Please please please* make our beloved grunt-contrib-less task utilizing `sourceMapRootpath` and `sourceMapBasepath` for the `sourceMappingURL` again. Thanks in advance.

**Comment by MarkyMarkNo1** [comment] 2015-01-05 16:04
P.S.: I see I could use `sourceMapURL` in addition for my task - but I agree with @MartinSGill , this would lead to unnecessary complexity for multiple equivalent operations. I'd keep it conservative, with less' default behaviour, as before v1.0.0, and intend `sourceMapURL` as additional option for cases where deviation from default is needed explicitly.

**Comment by HansHammel** [comment] 2015-02-03 18:24
still an issue, very annoying!

**Comment by kokarn** [comment] 2015-02-09 14:11
I can just confirm the other peoples findings. 
However, I can't get it to work with 0.12.0 either. 
Both versions work equally bad for me.

I manage to generate the style.css and style.css.map files in the correct dir but no matter what i do all the sources in the sourcemap are written with ```www/less/***.less```. 
As previously stated by @MarkyMarkNo1 changing the value of ```sourceMapBasepath``` doesn't do anything.

Structure
```
Gruntfile.js
node_modules/
www/
    css/
        style.css
        style.css.map
    less/
        main.less
```
Config
```
less: {
    default: {
        options: {
            sourceMap: true,
            sourceMapFilename: 'www/css/style.css.map',
            sourceMapURL: 'style.css.map',
            sourceMapBasepath: '../less/'
        },
        src: 'www/less/main.less',
        dest: 'www/css/style.css'
    }
}
```

Anybody working on this? Is there anything I can do to help out with this?

**Comment by MarkyMarkNo1** [comment] 2015-02-09 15:00
Have you tried

```javascript
sourceMapBasepath: 'www'
```

\- eventually combined with

```javascript
sourceMapRootpath: '/'
```

? Then your references should point to '/less/main.less' f.e.?

**Comment by kokarn** [comment] 2015-02-09 15:10
You are a genius, that works!
How come sourceMapBasepath doesn't do that? Is sourceMapRootpath needed for the basepath to be used?

**Comment by mithun-daa** [comment] 2015-02-12 17:09
Any updates on a fix for this issue? Other than reverting back to v0.12?

**Comment by BastianHofmann** [comment] 2015-02-13 11:28
@MarkyMarkNo1's solutions works for me also.

**Comment by Iwasawafag** [comment] 2015-02-27 23:20
Also faced this issue. I have config like this

```javascript
less: {
	development: {
		options: {
			relative_urls: true,
			sourceMap: true,
			//sourceMapRootpath: '../../../../',
			sourceMapRootpath: '../../../' // ugh, builds relative to Gruntfile for some reason
		},
		files: [
			{
				expand: true,
				src: ['../css/*.less', '!../css/vars-and-mixins.less'],
				dest: 'runtime/dev/css/',
				ext: '.css'
			}
		]
	},
	production: { /*...*/ }
}
```

(the idea was to mess with compiled files more after that, combine them all together at the end and place result back to `../css/`)

But after execution of the task I'm getting `/*# sourceMappingURL=runtime/dev/css/global.css.map */` at the end of the css file. Since css file itself located at `runtime/dev/css/` - it points at `runtime/dev/css/runtime/dev/css/global.css.map`.

Paths inside of the sourcemap itself also build related to the directory with less files, relative to the Gruntfile location, and not map file location. (`../css/` instead of `../../../../css/`)

So, if I want to use it as I intended - the only way for me at the moment is having result of compilation at the same location as less files, or hardcode paths to every less file. Which I'm not happy with

Change log says `sourceMapUrl` can accept a `function`, but it doesn't changes anything.

----------------------------------

Also, during execution it says:

```
File undefined created.
File runtime/dev/css/global.css created
File undefined created.
File runtime/dev/css/main.css created
```

what doesn't look right. Maybe it needs to be looked at.

**Comment by Iwasawafag** [comment] 2015-02-28 00:36
Oh, and... If I'm listing files through object (`{ 'dest/path': ['source/path'] }`) — paths inside of .map files are generating all correct. (it starts with `../../../../css/` as supposed to be, instead of `../css/` as it turns out in 1.0.0) So there's another error.

0.12.0 does not have this problem with file arrays as well, so I assume it is caused by the same reasons as incorrect sourceMappingURL.

~~What a trainwreck~~

**Comment by alampros** [comment] 2015-03-13 13:00
I can confirm that downgrading to `v0.12.0` got sourceMaps working correctly for my setup.

I have a hunch that it has to with configs that use grunt [expanded file mapping with the `cwd` option](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically).

**Comment by schmod** [comment] 2015-03-16 14:02
I've stepped through this with a debugger, and as far as I can tell, the issue actually might be on the LESS side of things -- there's some weirdness going on with the way that this plugin does src/dest mappings, and LESS is having trouble figuring out how to map the input basePath to the output URL.

I'd PR a fix, but I'm still having a tough time wrapping my head around the problem...

**Comment by schmod** [comment] 2015-03-16 14:03
Also worth noting that LESS's documentation on its supported SourceMap parameters is seemingly incomplete.  The source makes reference to a few parameters that aren't mentioned in the documentation.

**Comment by movrack** [comment] 2015-05-09 22:23
I also have some problem with the generated path for source map.
After reading all comments, I think there is a problem in the code. I don't know already what. I will explain later with my configuration (too late today) but I thing too there is some misunderstanding with documentation. Probably it is not enough well documented.

**Comment by nhall** [comment] 2015-06-05 04:28
I can confirm that `sourceMapRootpath` and `sourceMapBasepath` have no effect in 1.0.0. Doesn't matter what string I change these to it will never update the path set in the CSS output.

**Comment by roelvanduijnhoven** [comment] 2015-12-23 10:24
This seems like a serious bug! Still the documentation mentions these functions, and indeed they still do not work! Should we consider this repo to be dead?

**Comment by wroud** [comment] 2016-01-24 13:04
I found solution
```javascript
            development: {
                options: {
                    compress: true,
                    yuicompress: true,
                    optimization: 2,
                    sourceMap: true,
                    sourceMapURL: "interface.css.map",
                    sourceMapRootpath: "/",
                    sourceMapBasepath: function (f) {
                        this.sourceMapURL = this.sourceMapFilename.substr(this.sourceMapFilename.lastIndexOf('/') + 1);
                        return "wwwroot/";
                    },
                },
                expand: true,
                cwd: 'wwwroot/assets/less/',
                dest: 'wwwroot/css/',
                src: ['interface.less', 'blog.less'],
                ext: '.css'
            },```

**Comment by idhamperdameian** [comment] 2016-05-09 09:29
Same issue here.
Thanks to @Wroud, this working for me:
```
dev: {
    options: {
        strictMath: true,
        sourceMap: true,
        outputSourceFiles: true,
        sourceMapBasepath: function () {
            this.sourceMapURL = this.sourceMapFilename.substr(this.sourceMapFilename.lastIndexOf('/') + 1);
        }
    },
    files: [{
        expand: true,
        cwd: config.assetsDir + 'less',
        src: ['*.less'],
        dest: config.cssOutput,
        ext: '-dev.css'
    }]
}
```

**Comment by cyrfer** [comment] 2016-05-24 07:43
I decided to add map file support - What a night!

Thank you @Wroud! I am using this to fix the problem with the reference in css to the map file:

```javascript
sourceMapBasepath: function () {
    this.sourceMapURL = '/mybase/' + this.sourceMapFilename.substr(this.sourceMapFilename.lastIndexOf('/') + 1);
   return 'no_idea_but_it_works';
},
```

As others have pointed out, the map's `sources` get generated relative to the gruntfile instead of a path of my choosing. I tried setting the `cwd` for the grunt task, but no luck. `sourceMapRootpath` option DOES effect the `sources` in the .map file, but only prepends the path I wish to change.

I tried downgrading to v0.12.0, but that seems to not support less plugins, so I lose `less-plugin-group-css-media-queries`.

**Closed** 2016-08-09 07:47 UTC
