### ISSUE TITLE
calc issue

### ISSUE THREAD

**Issue by stevenvachon** [gruntjs/grunt-contrib-less#195] opened 2014-07-18 21:23 UTC
In the browser and the command-line with Less, I have no issues using `calc()`, but using grunt-contrib-less produces
```
>> OperationError: Operation on an invalid type in stylesheets/common.less on line 55, column 2:
>> 54 	overflow-x: hidden;
>> 55 	padding-top: calc( var(--header-height) + 1rem );
>> 56 	position: relative;
```

**Comment by gwicksted** [comment] 2015-09-10 19:37
Curious, does this work?

calc(var(--header-height) ~"+" 1rem);

**Comment by seven-phases-max** [comment] 2015-09-10 22:04
@gwicksted 

Yes, Less will compile `calc(var(--header-height) ~"+" 1rem);` to calc(var(--header-height) + 1rem); as expected.

**Comment by PawelOwczarekFalcon** [comment] 2016-03-17 13:53
I found solution:
http://gillianshelpdesk.tumblr.com/post/127773807047/calc-issues-in-grunt-contrib-less

**Comment by XhmikosR** [comment] 2016-07-21 19:25
Does this still happen with the latest release?

**Comment by rodrigobacelli** [comment] 2016-08-08 21:08
@XhmikosR yeah, unfortunately

**Comment by XhmikosR** [comment] 2016-08-09 07:30
I need a full test case I can use to reproduce this...

**Comment by XhmikosR** [comment] 2016-08-09 07:44
I can't reproduce this. I [added a test case](https://github.com/gruntjs/grunt-contrib-less/commit/5501c3b6fcbbe9b811e2cdf8aa6bf3d9d93d7020) and passes fine with the latest master, so I'm closing the issue.

**Closed by XhmikosR** 2016-08-09 07:44 UTC
